name: Publish Package to npmjs
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.17.3'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install -g typescript@4.9.5
      - name: Compile projects
        run: |
          chmod +x .github/workflows/build.sh
          .github/workflows/build.sh
        shell: bash
      - name: Publish package
        run: |
          cd ./build/core
          npm publish --access public --dry-run true
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}